GET http://localhost:8080
###
GET ticketing-app.up.railway.app:8080/users
###
GET http://localhost:8080/users
###

GET http://localhost:8080/users/delete/testi1ss
###






POST http://localhost:8080/users/login
Content-Type: application/json

{
    "username": "bob-admin",
    "password": "password"
}

