GET http://localhost:8080
###
GET https://t-app.up.railway.app/users/
###
GET https://t-app.up.railway.app/users/delete/test-user-1
###

GET http://localhost:8080/users/delete/testi1ss
###






POST https://t-app.up.railway.app/users/
Content-Type: application/json

{
    "username": "bob-admin",
    "password": "bob123",
    "role": "admin"
}

